src_dir:
    - "/group/project/summa/MGB1/evalVideo"
    #- bbcdataptn and - group summa are currently hardcoded
xml_dir: "/afs/inf.ed.ac.uk/group/cstr/datawww/asru/MGB1/data/xml"
filelist: "/afs/inf.ed.ac.uk/group/cstr/datawww/asru/MGB1/scripts/dev.full"
desired_genres:
    - "news"
    - "documentary"
    - "childrens"
    - "drama"
output_dir: '/disk/scratch/s1768177/pipeline/test_output_data/'
ctm: "/afs/inf.ed.ac.uk/group/ug4-projects/s1768177/AVSR/pipeline/dev.full.ref.ctm"
